### ISSUE TITLE
No mention of gpg compression in the docs

### ISSUE THREAD

**Issue by cippaciong** [holland-backup/holland-backup.github.com#1]
Hello, I was looking for a way to encrypt my backups with gpg and stumbled upon this PR https://github.com/holland-backup/holland/pull/95
It would be nice to mention that gpg is now available as compression target even in the docs.

**Comment by soulen3** [comment]
Hello,

I've included this in the following pull request.
https://github.com/holland-backup/holland-backup.github.com/pull/2

Thanks,
Steve

**Comment by cippaciong** [comment]
Thanks :)
