### ISSUE TITLE
Reference to mysqldump in pgdump section in Docs

### ISSUE THREAD

**Issue by mralexjuarez** [holland-backup/holland-backup.github.com#4]
Reference URL: http://docs.hollandbackup.org/provider_configs/pgdump.html

In the section for pgdump, there is a reference to mysqldump under inline compression.  It is included as part of the default compression include.

`.. include:: compression.txt
`

Not sure if inline is even an option for pgdump so I figure it could be handled in a few different ways.

**Comment by soulen3** [comment]
Thanks for the report.  I've update this for the 1.1.4 release to try and make it clearer.  The compression options are valid for pgdump, but only if you're using a format other than 'custom'
